---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: createuse:cluster:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get","list", "create", "delete"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: createuse:rule
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: []
