apiVersion: v1
kind: Pod
metadata:
  name: capture-api
  namespace: default
  labels:
    app: capture-api
spec:
  containers:
  - image: bydufish/capture_api
    name: capture-api
    volumeMounts:
    - name: nfs-volume
      mountPath: //mnt/telegram
  volumes:
  - name: nfs-volume
    nfs:
      server: 10.0.0.173
      path: /volume1/surveillance
