apiVersion: v1
kind: Service
metadata:
  name: capture-api-service
spec:
  type: NodePort
  selector:
    app: capture-api
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500
