apiVersion: v1
kind: Pod
metadata:
  name: camera-archive-pod
  namespace: default
  labels:
    app: camera-archive
spec:
  containers:
  - image: bydufish/archive
    name: camera-archive
    volumeMounts:
    - name: nfs-volume
      mountPath: //mnt/telegram
  volumes:
  - name: nfs-volume
    nfs:
      server: 10.0.0.173
      path: /volume1/surveillance
